// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SPM_Backend.Data;

#nullable disable

namespace SPM_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260804054639_IntialCreate")]
    partial class IntialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SPM_Backend.Models.SPM_ProjectAllocation", b =>
                {
                    b.Property<int>("ProjectAllocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectAllocationID"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("FacultyID")
                        .HasColumnType("int");

                    b.Property<string>("OverAllGrade")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("ProgressPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("ProjectEndDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProjectStartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("TotalCompletedTasks")
                        .HasColumnType("int");

                    b.Property<int>("TotalTasksGiven")
                        .HasColumnType("int");

                    b.HasKey("ProjectAllocationID");

                    b.HasIndex("FacultyID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("StudentID");

                    b.ToTable("SPM_ProjectAllocation");
                });

            modelBuilder.Entity("SPM_Backend.Models.SPM_ProjectMaster", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProjectID");

                    b.ToTable("SPM_ProjectMaster");
                });

            modelBuilder.Entity("SPM_Backend.Models.SPM_Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.ToTable("SPM_Role");
                });

            modelBuilder.Entity("SPM_Backend.Models.SPM_Task", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<decimal>("AssignedScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("EarnedScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("FacultyRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NextFollowUpDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("ProgressPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ProjectAllocationID")
                        .HasColumnType("int");

                    b.Property<string>("StudentRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("TaskAssignedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("TaskCompletedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TaskDueDate")
                        .HasColumnType("datetime");

                    b.Property<int>("TaskPriorityID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TaskStartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("TaskStatusID")
                        .HasColumnType("int");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TaskID");

                    b.HasIndex("ProjectAllocationID");

                    b.HasIndex("TaskPriorityID");

                    b.HasIndex("TaskStatusID");

                    b.ToTable("SPM_Task");
                });

            modelBuilder.Entity("SPM_Backend.Models.SPM_TaskPriority", b =>
                {
                    b.Property<int>("TaskPriorityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskPriorityID"));

                    b.Property<string>("TaskPriorityName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaskPriortyCssClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TaskPriortyCssClass");

                    b.HasKey("TaskPriorityID");

                    b.ToTable("SPM_TaskPriority");
                });

            modelBuilder.Entity("SPM_Backend.Models.SPM_TaskStatus", b =>
                {
                    b.Property<int>("TaskStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskStatusID"));

                    b.Property<string>("TaskStatusCssClass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TaskStatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TaskStatusID");

                    b.ToTable("SPM_TaskStatus");
                });

            modelBuilder.Entity("SPM_Backend.Models.SPM_User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicturePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserTypeID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserTypeID");

                    b.ToTable("SPM_User");
                });

            modelBuilder.Entity("SPM_Backend.Models.SPM_UserRole", b =>
                {
                    b.Property<int>("RolePermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolePermissionID"));

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("RolePermissionID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("SPM_UserRole");
                });

            modelBuilder.Entity("SPM_Backend.Models.SPM_UserType", b =>
                {
                    b.Property<int>("UserTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTypeID"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserTypeID");

                    b.ToTable("SPM_UserType");
                });

            modelBuilder.Entity("SPM_Backend.Models.SPM_ProjectAllocation", b =>
                {
                    b.HasOne("SPM_Backend.Models.SPM_User", "Faculty")
                        .WithMany("FacultyAllocations")
                        .HasForeignKey("FacultyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SPM_Backend.Models.SPM_ProjectMaster", "Project")
                        .WithMany("ProjectAllocations")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SPM_Backend.Models.SPM_User", "Student")
                        .WithMany("StudentAllocations")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Project");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SPM_Backend.Models.SPM_Task", b =>
                {
                    b.HasOne("SPM_Backend.Models.SPM_ProjectAllocation", "ProjectAllocation")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectAllocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SPM_Backend.Models.SPM_TaskPriority", "TaskPriority")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskPriorityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SPM_Backend.Models.SPM_TaskStatus", "TaskStatus")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskStatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProjectAllocation");

                    b.Navigation("TaskPriority");

                    b.Navigation("TaskStatus");
                });

            modelBuilder.Entity("SPM_Backend.Models.SPM_User", b =>
                {
                    b.HasOne("SPM_Backend.Models.SPM_UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("SPM_Backend.Models.SPM_UserRole", b =>
                {
                    b.HasOne("SPM_Backend.Models.SPM_Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SPM_Backend.Models.SPM_User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SPM_Backend.Models.SPM_ProjectAllocation", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("SPM_Backend.Models.SPM_ProjectMaster", b =>
                {
                    b.Navigation("ProjectAllocations");
                });

            modelBuilder.Entity("SPM_Backend.Models.SPM_Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SPM_Backend.Models.SPM_TaskPriority", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("SPM_Backend.Models.SPM_TaskStatus", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("SPM_Backend.Models.SPM_User", b =>
                {
                    b.Navigation("FacultyAllocations");

                    b.Navigation("StudentAllocations");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SPM_Backend.Models.SPM_UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
